### ISSUE TITLE
test functions

### ISSUE THREAD

**Issue by Konfekt** [vitalk/vim-shebang#4]
The test functions such as

```
https://github.com/vitalk/vim-shebang/blob/master/autoload/shebang.vim#L17
```

do not seem necessary for `vim-shebang` to detect the proper filetype. 

How about putting them into a separate `test` folder instead of `autolad`?

**Comment by vitalk** [comment]
Hi @Konfekt.

Good note and I agreed that keeping tests independent from plugin itself is better then the current way I handle them. But there is no overhead for endpoint users (vim don’t load functions from `autoload` directory until they are required) and I can can use a handy way to launch test suite

``` viml
:call shebang#unittest()
```

So I keep them as is and thank you for your attentiveness.
