### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [vitalk/vim-shebang#5]
This file does not get detected

```python
#/usr/bin/env python

print('Hello worlds')
```

What needs to be done to make this plugin work with modern (neo)vim scripts?

**Comment by vitalk** [comment]
Hi @Th3Whit3Wolf 

The shebang line should start from `#!`, e.g.

```sh
#!/usr/bin/env python 
```

If you want to add additional pattern support please use the following command

```
AddShebangPattern! python whatever/pattern/you/want/to/add
```

**Comment by Th3Whit3Wolf** [comment]
Dear Lord I can't believe I missed the bang in shebang. I am terribly sorry for bothering you. Thank you for your time good sir.
